Single Linked List
hahahania/LinkedLists pull request #1
Opened 2023-02-07 15:30 UTC by hahahania

Napisałam pierwszą linked list. Musiałam sobie dawać komentarze, żeby lepiej zrozumieć

2023-02-07 16:13 UTC, Zwo1in commented on linkedlist.py
> +        if self.head == None:
```suggestion
        if self.head is None:
```

Do porownan z none powinnas uzywac `is` i `is not`
https://stackoverflow.com/a/14247383

2023-02-07 16:46 UTC, Zwo1in commented on linkedlist.py
> +    def insert_at_index(self, data, index):
Chyba nie zadziala jesli lista jest pusta:
```
a = LinkedList()
a.insert_at_index("foo", 0)
```

2023-02-07 16:49 UTC, Zwo1in commented on linkedlist.py
> +            self.head = self.head.next
tu tez masz buga przy niewypelnionej liscie

2023-02-07 16:50 UTC, Zwo1in commented on linkedlist.py
> +    def deleting_at_index(self, index):
```suggestion
    def delete_at_index(self, index):
```

be consistent :grin:

2023-02-07 16:55 UTC, Zwo1in commented on linkedlist.py
> +    def insert_at_index(self, data, index):
hmm, chyba w ogole nie zadziala dla zera

2023-02-07 16:57 UTC, Zwo1in commented on linkedlist.py
> +                current.next = current.next.next
tu chyba tez da sie to popsuc jesli kaze sie usunac ostatni element, `current.next.next` chyba walnie

2023-02-07 16:58 UTC, Zwo1in requested changes
left some issues, dobry case zeby pocwiczyc sobie testy :wink:

2023-02-08 15:16 UTC, Zwo1in commented on linkedlist.py
> +    def list_lenght(self):
Generalnie fajnie, ze napisalas te metode w ten sposob dla treningu, ale wydaje mi sie, ze najlepszym rozwiazaniem byloby, zeby trzymac to jako propercje bezposrednio w klasie i trackowac kiedy dodajesz lub usuwasz element. W ten sposob bedziesz mogla latwiej robic jakies sprawdzenia w tych metodach z indexami bez zwiekszania zlozonosci obliczeniowej

2023-02-08 16:10 UTC, hahahania commented on linkedlist.py
> +    def insert_at_index(self, data, index):
faktycznie 😱

2023-02-08 17:14 UTC, Zwo1in commented on linkedlist.py
> +        self.next = next
dla takich klas ktore sa tylko wraperami na dane, tzn nie zawieraja (prawie) zadnej szczegolnej logiki itp, warto stosowac taki wrapper [dataclass](https://docs.python.org/3/library/dataclasses.html). To sprawi, ze automatycznie wygeneruje ci sie `__init__` i pare innych podstawowych funkcji, jak np porownania `==` itd

```python
from dataclasses import dataclass

@dataclass
class Node:
    data: Any
    next: Optional["Node"]  # tu typ jest w ciapkach, poniewaz jeszcze nie skonczyla sie deklaracja `Node`, wiec jeszcze nie za bardzo mozna go uzyc, to ten 'hack' w pythonie o ktorym ci pisalem
```
![image](https://user-images.githubusercontent.com/34972409/217602669-7d4eece1-54ff-4250-a136-36ff5117a18d.png)

2023-02-13 10:57 UTC, Zwo1in approved these changes
lgtm

2023-02-13 11:06 UTC, merged